import { jsPDF } from 'jspdf'

export interface RemediationData {
    summary: string
    warnings: string[]
    remediations: Record<string, string>
}

export function generateNDISAddendum(data: RemediationData) {
    // A4 document
    const doc = new jsPDF()
    const pageWidth = doc.internal.pageSize.getWidth()
    const pageHeight = doc.internal.pageSize.getHeight()
    const margin = 20

    // Page constraints
    const maxLineWidth = pageWidth - margin * 2

    // Helper: Draw page border
    const drawPageBorder = () => {
        doc.setDrawColor(200, 200, 200)
        doc.rect(10, 10, pageWidth - 20, pageHeight - 20)
    }

    drawPageBorder()

    // Fonts & Colors
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(15, 23, 42) // Slate-900

    // Header
    doc.setFontSize(16)
    doc.text('NDIS SERVICE AGREEMENT ADDENDUM', pageWidth / 2, 30, { align: 'center' })

    // Subheader
    doc.setFont('helvetica', 'italic')
    doc.setFontSize(10)
    doc.setTextColor(100, 116, 139) // Slate-500
    doc.text('Generated by PylonChat Sovereign AI - Sydney Region (ap-southeast-2)', pageWidth / 2, 40, { align: 'center' })

    doc.setDrawColor(226, 232, 240) // Slate-200
    doc.line(margin, 45, pageWidth - margin, 45)

    // Body
    let cursorY = 55
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(51, 65, 85) // Slate-700
    doc.setFontSize(10)

    // Helper: Check page break
    const checkPageBreak = (neededHeight: number) => {
        if (cursorY + neededHeight > pageHeight - 30) {
            doc.addPage()
            drawPageBorder()
            cursorY = 30
        }
    }

    // Add Introduction
    const introText = "This document identifies specific compliance gaps in the provided Service Agreement and outlines active remediations designed to meet NDIS 2025/26 requirements."
    const splitIntro = doc.splitTextToSize(introText, maxLineWidth)
    doc.text(splitIntro, margin, cursorY)
    cursorY += (splitIntro.length * 5) + 10

    // Render each suggestion
    data.warnings.forEach((warning, idx) => {
        const remediation = data.remediations[warning]
        if (!remediation) return

        checkPageBreak(30)

        // Gap Title
        doc.setFont('helvetica', 'bold')
        doc.setTextColor(245, 158, 11) // Amber-500
        const gapTitle = `Gap ${idx + 1}: ${warning}`
        const splitTitle = doc.splitTextToSize(gapTitle, maxLineWidth)
        doc.text(splitTitle, margin, cursorY)
        cursorY += (splitTitle.length * 5) + 3

        // Wording Header
        doc.setFont('helvetica', 'bold')
        doc.setTextColor(15, 118, 110) // Teal-700
        doc.setFontSize(9)
        doc.text('Suggested Compliance Wording:', margin, cursorY)
        cursorY += 6

        // Actual wording
        doc.setFont('helvetica', 'normal')
        doc.setTextColor(51, 65, 85) // Slate-700
        doc.setFontSize(9)

        // Strip markdown bold asterisks for PDF (simple stripping)
        const cleanRemediation = remediation.replace(/\*\*/g, '')
        const splitRemediation = doc.splitTextToSize(cleanRemediation, maxLineWidth - 10)

        // Background box for remediation
        const boxHeight = (splitRemediation.length * 4) + 6
        checkPageBreak(boxHeight + 10)

        doc.setFillColor(248, 250, 252) // Slate-50
        doc.setDrawColor(226, 232, 240) // Slate-200
        doc.rect(margin + 2, cursorY - 4, maxLineWidth - 4, boxHeight, 'FD')

        doc.text(splitRemediation, margin + 5, cursorY)
        cursorY += boxHeight + 8
    })

    // Signature Block
    checkPageBreak(50)
    cursorY += 10
    doc.setDrawColor(226, 232, 240)
    doc.line(margin, cursorY, pageWidth - margin, cursorY)
    cursorY += 10

    doc.setFont('helvetica', 'bold')
    doc.setTextColor(15, 23, 42)
    doc.setFontSize(10)
    doc.text('Signatures', margin, cursorY)
    cursorY += 15

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)

    // Provider line
    doc.text('Provider Representative:', margin, cursorY)
    doc.line(margin + 45, cursorY + 1, margin + 100, cursorY + 1)

    // Participant line
    doc.text('Participant / Nominee:', margin + 110, cursorY)
    doc.line(margin + 150, cursorY + 1, pageWidth - margin, cursorY + 1)

    // Footer
    const totalPages = doc.getNumberOfPages()
    for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i)
        doc.setFont('helvetica', 'italic')
        doc.setFontSize(8)
        doc.setTextColor(148, 163, 184) // Slate-400
        const footerText = `Data Sovereignty Guaranteed: Processed in Australia East. This document is a suggestion and not legal advice. | Page ${i} of ${totalPages}`
        doc.text(footerText, pageWidth / 2, pageHeight - 15, { align: 'center' })
    }

    // Trigger download
    doc.save('PylonChat_NDIS_Addendum.pdf')
}
