import { jsPDF } from 'jspdf'
import 'jspdf-autotable'

export interface RemediationData {
    summary: string
    warnings: string[]
    remediations: Record<string, string>
    filename: string
}

export function generateNDISAddendum(data: RemediationData) {
    // A4 document
    const doc = new jsPDF()
    const pageWidth = doc.internal.pageSize.getWidth()
    const pageHeight = doc.internal.pageSize.getHeight()
    const margin = 20
    const maxLineWidth = pageWidth - margin * 2

    // Helper: Draw page border
    const drawPageBorder = () => {
        doc.setDrawColor(200, 200, 200)
        doc.rect(10, 10, pageWidth - 20, pageHeight - 20)
    }

    drawPageBorder()

    // ── Header ──
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(15, 23, 42) // Slate-900
    doc.setFontSize(18)
    doc.text('NDIS COMPLIANCE ADDENDUM', pageWidth / 2, 30, { align: 'center' })

    doc.setFont('helvetica', 'italic')
    doc.setFontSize(10)
    doc.setTextColor(100, 116, 139) // Slate-500
    doc.text('Generated by PylonChat Sovereign AI - Sydney Region (ap-southeast-2)', pageWidth / 2, 38, { align: 'center' })

    doc.setDrawColor(226, 232, 240) // Slate-200
    doc.line(margin, 43, pageWidth - margin, 43)

    let cursorY = 53

    // ── Scope of Application & Provider Identity ──
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(15, 23, 42)
    doc.setFontSize(11)
    doc.text('Scope of Application', margin, cursorY)
    cursorY += 6

    doc.setFont('helvetica', 'normal')
    doc.setTextColor(51, 65, 85)
    doc.setFontSize(10)

    const scopeText = `This addendum modifies the original Service Agreement (${data.filename || 'Original_Document.pdf'}) to meet NDIS 2025/26 requirements and immediate compliance standards.`
    const splitScope = doc.splitTextToSize(scopeText, maxLineWidth)
    doc.text(splitScope, margin, cursorY)
    cursorY += (splitScope.length * 5) + 6

    // Provider Identity Box (Injected ABN)
    doc.setFillColor(248, 250, 252) // Slate-50
    doc.setDrawColor(203, 213, 225) // Slate-300
    doc.rect(margin, cursorY, maxLineWidth, 20, 'FD')

    doc.setFont('helvetica', 'bold')
    doc.setFontSize(9)
    doc.text('Provider Identity:', margin + 4, cursorY + 8)

    doc.setFont('helvetica', 'normal')
    doc.text('Hireup Pty Ltd (ABN: 32 600 120 711)', margin + 35, cursorY + 8)

    doc.text('Document Status:', margin + 4, cursorY + 14)
    doc.setTextColor(15, 118, 110) // Teal-700
    doc.text('Active Fix Addendum', margin + 35, cursorY + 14)

    cursorY += 28

    // ── Active Fixes Table ──
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(15, 23, 42)
    doc.setFontSize(11)
    doc.text('Mandated Remediation Clauses', margin, cursorY)
    cursorY += 6

    const tableBody = data.warnings
        .filter(warning => data.remediations && data.remediations[warning])
        .map((warning, idx) => {
            const cleanRemediation = data.remediations[warning].replace(/\*\*(.*?)\*\*/g, '$1') // Strip markdown bold
            return [`Gap ${idx + 1}:\n${warning}`, cleanRemediation]
        })

    // @ts-ignore - jspdf-autotable attaches to doc
    doc.autoTable({
        startY: cursorY,
        head: [['Identified Compliance Gap', 'Remediation Wording (Active Fix)']],
        body: tableBody,
        theme: 'grid',
        headStyles: {
            fillColor: [15, 23, 42], // Slate-900
            textColor: 255,
            fontSize: 9,
            fontStyle: 'bold'
        },
        bodyStyles: {
            fontSize: 9,
            textColor: [51, 65, 85], // Slate-700
            cellPadding: 4,
            valign: 'top'
        },
        columnStyles: {
            0: { cellWidth: 50, fontStyle: 'bold' },
            1: { cellWidth: 'auto' }
        },
        margin: { left: margin, right: margin, top: 25, bottom: 30 }, // Account for headers/footers
        didDrawPage: (hookData: any) => {
            // Re-draw border on new pages created by autotable
            drawPageBorder()
        }
    })

    // @ts-ignore
    cursorY = doc.lastAutoTable.finalY + 20

    // Helper: Check page break for signature block
    if (cursorY + 60 > pageHeight - 30) {
        doc.addPage()
        drawPageBorder()
        cursorY = 30
    }

    // ── Signature Block ──
    doc.setDrawColor(226, 232, 240)
    doc.line(margin, cursorY, pageWidth - margin, cursorY)
    cursorY += 10

    doc.setFont('helvetica', 'bold')
    doc.setTextColor(15, 23, 42)
    doc.setFontSize(11)
    doc.text('Execution & Agreement', margin, cursorY)
    cursorY += 12

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9)
    doc.setTextColor(51, 65, 85)

    const sigBoxWidth = (maxLineWidth / 2) - 5

    // Function to draw a signature box
    const drawSignatureBox = (xOffset: number, title: string) => {
        doc.setFont('helvetica', 'bold')
        doc.text(title, xOffset, cursorY)

        doc.setFont('helvetica', 'normal')

        // Full Name
        doc.text('Full Name:', xOffset, cursorY + 12)
        doc.setDrawColor(203, 213, 225)
        doc.line(xOffset + 20, cursorY + 13, xOffset + sigBoxWidth, cursorY + 13)

        // Signature
        doc.text('Signature:', xOffset, cursorY + 24)
        doc.line(xOffset + 20, cursorY + 25, xOffset + sigBoxWidth, cursorY + 25)

        // Date
        doc.text('Date:', xOffset, cursorY + 36)
        doc.line(xOffset + 20, cursorY + 37, xOffset + sigBoxWidth, cursorY + 37)
    }

    drawSignatureBox(margin, 'Provider Representative')
    drawSignatureBox(margin + sigBoxWidth + 10, 'Participant / Nominated Representative')

    // ── Footer & Watermarks ──
    const totalPages = doc.getNumberOfPages()
    for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i)

        // Watermark / Sovereign Stamp
        doc.setFont('helvetica', 'normal')
        doc.setFontSize(8)
        doc.setTextColor(148, 163, 184) // Slate-400

        // Corner text (top right)
        doc.text('Verified by PylonChat Sovereign AI | Region: ap-southeast-2 (Sydney)', pageWidth - margin, 16, { align: 'right' })

        // Bottom Footer
        const footerText = `Data Sovereignty Guaranteed: Processed in Australia East. This document is a suggestion and not legal advice. | Page ${i} of ${totalPages}`
        doc.text(footerText, pageWidth / 2, pageHeight - 15, { align: 'center' })
    }

    // Trigger download
    doc.save('PylonChat_NDIS_Addendum.pdf')
}
