import type { Metadata } from 'next'
import Link from 'next/link'
import { PublicNav } from '@/components/layout/PublicNav'
import { Footer } from '@/components/Footer'
import {
    AlertTriangle,
    CheckCircle2,
    FileText,
    ShieldCheck,
    ArrowRight,
    Lock,
} from 'lucide-react'

export const metadata: Metadata = {
    title: 'Sample Audit Report — Steve Day Services | PylonChat',
    description:
        'See a real example of what an AI-generated NDIS compliance audit looks like. This sample report for Steve Day Services highlights missing clauses and auto-generated addendum text.',
}

const GAPS = [
    {
        severity: 'critical' as const,
        tag: '[MISSING ABN]',
        detail: 'No ABN or ACN found for the provider. Required under NDIS Practice Standards s.1.1.',
    },
    {
        severity: 'critical' as const,
        tag: '[NO CANCELLATION POLICY]',
        detail: 'Cancellation and short-notice policy is absent. NDIA price guide requires a minimum 48-hour notice clause.',
    },
    {
        severity: 'warning' as const,
        tag: '[GENERIC CONSENT CLAUSE]',
        detail: 'Consent language is non-specific. Participant consent for data sharing must reference the NDIS Act 2013.',
    },
    {
        severity: 'warning' as const,
        tag: '[NO COMPLAINT PATHWAY]',
        detail: 'No reference to the NDIS Quality and Safeguards Commission complaint process (required since Jul 2023).',
    },
]

const FIXES = [
    'ABN 12 345 678 901 confirmed and inserted into header',
    '48-hour cancellation policy added (NDIA-compliant wording)',
    'Participant consent clause updated to reference NDIS Act 2013 s.67',
    'Complaint pathway paragraph added with NDIS Commission contact details',
]

export default async function DemoReportPage({
    params,
}: {
    params: Promise<{ locale: string }>
}) {
    const { locale } = await params

    return (
        <>
            <PublicNav />

            <main className="min-h-screen bg-slate-50">
                {/* Page header */}
                <div className="bg-slate-900 text-white py-16">
                    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
                        <span className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-amber-500/10 border border-amber-500/20 text-amber-300 text-xs font-semibold uppercase tracking-wider mb-6">
                            <FileText className="w-3.5 h-3.5" />
                            Example Audit Report
                        </span>
                        <h1 className="text-4xl font-bold mb-4">Steve Day Services Pty Ltd</h1>
                        <p className="text-slate-400 max-w-xl mx-auto">
                            This is a sample NDIS service agreement audit generated by PylonChat.
                            It shows the kinds of compliance gaps our AI detects automatically.
                        </p>
                    </div>
                </div>

                <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-10">

                    {/* Score card */}
                    <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-8 flex flex-col sm:flex-row items-center gap-8">
                        <div className="flex-shrink-0 w-28 h-28 rounded-full border-8 border-red-200 bg-red-50 flex flex-col items-center justify-center shadow-inner">
                            <span className="text-3xl font-extrabold text-red-600">38</span>
                            <span className="text-xs font-semibold text-red-400 uppercase tracking-wide">/ 100</span>
                        </div>
                        <div>
                            <p className="text-sm font-semibold text-red-500 uppercase tracking-wider mb-1">
                                Non-Compliant — Immediate action required
                            </p>
                            <h2 className="text-xl font-bold text-slate-900 mb-2">
                                4 compliance gaps detected
                            </h2>
                            <p className="text-slate-500 text-sm leading-relaxed">
                                The document fails to meet NDIS Practice Standards 2025/26 on four key
                                criteria. Our AI has generated an addendum that fixes all issues.
                            </p>
                        </div>
                    </div>

                    {/* Gap list */}
                    <div>
                        <h2 className="text-lg font-bold text-slate-900 mb-4 flex items-center gap-2">
                            <AlertTriangle className="w-5 h-5 text-amber-500" />
                            Gaps Found
                        </h2>
                        <div className="space-y-3">
                            {GAPS.map((gap) => (
                                <div
                                    key={gap.tag}
                                    className={`flex items-start gap-4 p-4 rounded-xl border font-mono text-sm ${gap.severity === 'critical'
                                            ? 'bg-red-50 border-red-200 text-red-800'
                                            : 'bg-amber-50 border-amber-200 text-amber-800'
                                        }`}
                                >
                                    <AlertTriangle className="w-4 h-4 shrink-0 mt-0.5" />
                                    <div>
                                        <p className="font-bold mb-0.5">{gap.tag}</p>
                                        <p className="font-sans font-normal text-xs opacity-80 leading-relaxed">
                                            {gap.detail}
                                        </p>
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>

                    {/* After: auto-generated fixes */}
                    <div>
                        <h2 className="text-lg font-bold text-slate-900 mb-4 flex items-center gap-2">
                            <ShieldCheck className="w-5 h-5 text-cyan-500" />
                            Auto-Generated Addendum — fixes applied
                        </h2>
                        <div className="bg-white rounded-2xl border border-cyan-100 shadow-sm overflow-hidden">
                            <div className="p-6 border-l-4 border-cyan-400">
                                <p className="text-xs font-semibold text-cyan-700 uppercase tracking-wider mb-4">
                                    NDIS Service Agreement — Compliance Addendum
                                </p>
                                <ul className="space-y-3">
                                    {FIXES.map((fix) => (
                                        <li key={fix} className="flex items-start gap-3 text-sm text-slate-700">
                                            <CheckCircle2 className="w-5 h-5 text-cyan-500 shrink-0 mt-0.5" />
                                            {fix}
                                        </li>
                                    ))}
                                </ul>
                            </div>
                            {/* Blurred preview gate */}
                            <div className="relative px-6 pb-6">
                                <div className="space-y-3 opacity-30 blur-sm pointer-events-none select-none mt-4">
                                    <div className="h-3 bg-slate-200 rounded w-full" />
                                    <div className="h-3 bg-slate-200 rounded w-5/6" />
                                    <div className="h-3 bg-slate-200 rounded w-4/6" />
                                </div>
                                <div className="absolute inset-0 flex items-center justify-center">
                                    <div className="flex items-center gap-2 bg-slate-900/80 text-white px-4 py-2 rounded-full text-xs font-semibold backdrop-blur-sm">
                                        <Lock className="w-3.5 h-3.5" />
                                        Full addendum text visible after sign-up
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    {/* CTA */}
                    <div className="bg-slate-900 rounded-2xl p-8 text-center text-white">
                        <h3 className="text-2xl font-bold mb-3">Ready to audit your own agreement?</h3>
                        <p className="text-slate-400 mb-6 text-sm max-w-md mx-auto">
                            Upload your NDIS service agreement and get a full compliance report in under
                            60 seconds. Free to start — no credit card required.
                        </p>
                        <div className="flex flex-col sm:flex-row gap-4 justify-center">
                            <Link
                                href={`/${locale}/dashboard/validator`}
                                className="inline-flex items-center justify-center gap-2 px-8 py-3.5 bg-cyan-600 hover:bg-cyan-500 text-white font-bold rounded-xl transition-all group"
                            >
                                <ShieldCheck className="w-5 h-5" />
                                Audit My Agreement
                                <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
                            </Link>
                            <Link
                                href={`/${locale}/pricing`}
                                className="inline-flex items-center justify-center gap-2 px-8 py-3.5 bg-slate-800 hover:bg-slate-700 border border-slate-700 text-white font-medium rounded-xl transition-all"
                            >
                                View Pricing
                            </Link>
                        </div>
                    </div>

                </div>
            </main>

            <Footer locale={locale} />
        </>
    )
}
